[package]
name = "bassielight"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "0.2"
midir = "0.9.1"
rusb = "0.9.3"
rust-embed="8.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wry = "0.34"
